name: npm test
on: [push, pull_request]

name: npm test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  npm-publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm run build
      - run: npm test
